export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const DISPATCH_USERNAME = 'DISPATCH_USERNAME';
export const DISPATCH_EMAIL = 'DISPATCH_EMAIL';
export const DISPATCH_PASSWORD = 'DISPATCH_PASSWORD';
export const DISPATCH_REPASSWORD = 'DISPATCH_REPASSWORD';
export const DISPATCH_SHIPPING_REGION_ID = 'DISPATCH_SHIPPING_REGION_ID';
export const DISPATCH_INVALID = 'DISPATCH_INVALID';
