export const INITIAL_LANDING_VIEW_REQUEST = 'INITIAL_LANDING_VIEW_REQUEST';
export const INITIAL_LANDING_VIEW_SUCCESS = 'INITIAL_LANDING_VIEW_SUCCESS';
export const INITIAL_LANDING_VIEW_FAILURE = 'INITIAL_LANDING_VIEW_FAILURE';

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const GET_PRODUCTS_BY_CATEGORY_REQUEST =
  'GET_PRODUCTS_BY_CATEGORY_REQUEST';
export const GET_PRODUCTS_BY_CATEGORY_FAILURE =
  'GET_PRODUCTS_BY_CATEGORY_FAILURE';
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS =
  'GET_PRODUCTS_BY_CATEGORY_SUCCESS';

export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
