export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAILURE = 'GET_PRODUCT_BY_ID_FAILURE';

export const DISPATCH_QUANTITY = 'DISPATCH_QUANTITY';
export const DISPATCH_COLOR = 'DISPATCH_COLOR';
export const DISPATCH_SIZE = 'DISPATCH_SIZE';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const ADD_ITEM_FALSE = 'ADD_ITEM_FALSE';
