export const ADD_ITEM_IN_CART = 'ADD_ITEM_IN_CART';
export const SHOW_CART_DLG = 'SHOW_CART_DLG';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';
export const SET_CHECKEDOUT_ITEMS = 'SET_CHECKEDOUT_ITEMS';
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const LOGOUT = 'LOGOUT';
export const SET_LOGIN_TOKEN = 'SET_LOGIN_TOKEN';
export const INCREASE_PAGE_NUMBER = 'INCREASE_PAGE_NUMBER';
export const DECREASE_PAGE_NUMBER = 'DECREASE_PAGE_NUMBER';
export const SHOW_CATEGORY_ITEMS = 'SHOW_CATEGORY_ITEMS';
export const RESET_PAGE_NUMBER = 'RESET_PAGE_NUMBER';
export const RESET_STORE_AFTER_ORDER = 'RESET_STORE_AFTER_ORDER'
export const POST_ORDER_POPUP = 'POST_ORDER_POPUP'

export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAILURE = 'GET_ALL_CATEGORIES_FAILURE';

export const GET_CONFIGURATIONS_REQUEST = 'GET_CONFIGURATIONS_REQUEST';
export const GET_CONFIGURATIONS_SUCCESS = 'GET_CONFIGURATIONS_SUCCESS';
export const GET_CONFIGURATIONS_FAILURE = 'GET_CONFIGURATIONS_FAILURE';

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';

export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAILURE = 'GET_PRODUCT_BY_ID_FAILURE';

export const GET_PRODUCTS_BY_CATEGORY_REQUEST =
  'GET_PRODUCTS_BY_CATEGORY_REQUEST';
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS =
  'GET_PRODUCTS_BY_CATEGORY_SUCCESS';
export const GET_PRODUCTS_BY_CATEGORY_FAILURE =
  'GET_PRODUCTS_BY_CATEGORY_FAILURE';

export const GET_USER_INFORMATION_REQUEST = 'GET_USER_INFORMATION_REQUEST';
export const GET_USER_INFORMATION_SUCCESS = 'GET_USER_INFORMATION_SUCCESS';
export const GET_USER_INFORMATION_FAILURE = 'GET_USER_INFORMATION_FAILURE';

export const UPDATE_USER_INFORMATION_REQUEST =
  'UPDATE_USER_INFORMATION_REQUEST';
export const UPDATE_USER_INFORMATION_SUCCESS =
  'UPDATE_USER_INFORMATION_SUCCESS';
export const UPDATE_USER_INFORMATION_FAILURE =
  'UPDATE_USER_INFORMATION_FAILURE';

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST'
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'
export const PLACE_ORDER_FAILURE = 'PLACE_ORDER_FAILURE'